[project]
authors = [{name = "Saito Tsutomu", email = "tsutomu7@hotmail.co.jp"}]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
dependencies = [
  "pyvrp>=0.13.4",
]
description = "Solving the Traveling Salesman Problem"
name = "simple-tsp"
readme = "README.md"
requires-python = ">=3.12"
version = "0.2.1"

[project.urls]
homepage = "https://github.com/SaitoTsutomu/simple-tsp"

[dependency-groups]
dev = [
  "pytest>=9.0.3",
]

[tool.taskipy.tasks]
lint = "pyrefly check src && ruff check"
test = "uv run pytest"

[tool.uv]
exclude-newer = "3 days"

[[tool.uv.index]]
default = true
url = "https://pypi.flatt.tech/simple/"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.pyrefly]
project-includes = ["src"]

[tool.ruff]
src = ["src"]

[tool.ruff.lint]
ignore = [
  "missing-trailing-comma",
  "CPY",
  "incorrect-blank-line-before-class",
  "multi-line-summary-second-line",
  "missing-trailing-period",
  "missing-terminal-punctuation",
  "docstring-missing-returns",
  "line-too-long",
]
preview = true
select = ["ALL"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.12.0,<0.13.0"]
